# Generated by Django 4.1.7 on 2023-03-04 02:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom ')),
                ('status', models.CharField(choices=[('top', 'Paroisse'), ('second', 'Station secondaire')], max_length=30, verbose_name='Status')),
                ('archdiocese', models.CharField(max_length=30, verbose_name='Archidiocèse ')),
                ('priest', models.CharField(max_length=100, verbose_name='Curé ')),
                ('mother_parish', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paroisse mère ')),
                ('tmoney_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numéro Tmoney')),
                ('flooz_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numéro Flooz')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_church', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Contenu ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('suggestion_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_church', to='request.church')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='ChurchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30, verbose_name='Demandée par ')),
                ('content', models.TextField(max_length=200, verbose_name='Intention (Veuillez être clair, précis et bref)\n')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('hours', models.CharField(choices=[('DN', '6h'), ('MN', '9h'), ('MD', '12h'), ('EV', '17h')], max_length=3, verbose_name='Horaires ')),
                ('status', models.CharField(choices=[('NW', 'New'), ('RP', 'Reported')], default='NW', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_church', to='request.church')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre ')),
                ('content', models.CharField(max_length=200, verbose_name='Contenu ')),
                ('illustration', models.ImageField(blank=True, default=None, null=True, upload_to='images/illustrations/%Y/%m/%d/')),
                ('announcement_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_church', to='request.church')),
            ],
        ),
        migrations.AddIndex(
            model_name='churchrequest',
            index=models.Index(fields=['-status'], name='request_chu_status_3247df_idx'),
        ),
    ]
